### ISSUE TITLE
jump list not taken into account with auto_jump

### ISSUE THREAD

**Issue by dessaya** [folke/trouble.nvim#143]
When jumping with `Trouble lsp_definitions` having `auto_jump` enabled, the jump list is not taken into account. Pressing `<C-o>` should take the cursor back to the original position; instead it goes to whatever was on the jump list before that.

I think this only happens when jumping in the same file, not when jumping across different files.

**Comment by JulesNP** [comment]
I'm currently working around this issue by manually setting a jumplist location before calling trouble:

```lua
function()
    vim.cmd [[normal m']]
    trouble.close()
    trouble.open "lsp_definitions"
end
```

**Comment by Aex12** [comment]
Same issue here. It's so frustrating. At the moment I just use the builtin 'vim.lsp.buf.definition' lua function to jump to definitions and use a different binding to use Trouble

**Comment by Hubro** [comment]
So THIS is the cause! The last couple of months this has frustrated the hell out of me, sometimes my "previous position" is just the top of the current file, meaning I completely lose my flow. It only dawned on me today that this happens whenever I "go to definition" (<kbd>g</kbd><kbd>d</kbd>).

This issue has been open since 2021, I guess I'm setting my LSP mappings back to default :laughing:

**Comment by Hubro** [comment]
I stand corrected

**Comment by folke** [comment]
Yeah, sorry for the delay. I actualy use Telescope's go to definition myself, so didn't have this issue :)
