### ISSUE TITLE
The future of this repo

### ISSUE THREAD

**Issue by bellini666** [folke/trouble.nvim#180]
Hi,

First of all, I really love trouble (pun intended?) and think it is an awesome plugin! I moved all my quickfix/loclist workflow to use trouble instead for some time now and am totally happy with it.

I noticed that trouble development stopped since the beginning of the year. Not only from the author, but all PRs opened since them are waiting for some time to be reviewed/merged (5 of those are actually mine).

I don't know if @folke lost interest in this project or doesn't have time to maintain it anymore. Either way, it is totally his business and that's totally fine!! But it would be nice to know if that's the case so something can be done to repo itself. Like, someone (or a group of people) could take the role of maintainers? Or even a fork is needed to move on with new features and improvements?

**Comment by uncomfyhalomacro** [comment]
@bellini666 is their any fork that actively maintains it from now on that you know of?

**Comment by bellini666** [comment]
> @bellini666 is there any fork that actively maintains it from now on that you know of?

Not that I know of. I have a fork in my account which I merged my PRs that are waiting to be reviewed in this repo so that I could use it in my dotfiles, but I don't know if it should be the main fork from now on.

**Comment by HungryJoe** [comment]
I also love this plugin and don't want to see it die! How about we make an organization dedicated to maintaining it, a la [telescope](https://github.com/nvim-telescope)? I'd be happy to do this, but I'd like buy-in from at least @folke and @bellini666 before taking any action.

**Comment by bellini666** [comment]
@HungryJoe actually I'm only the one who created this issue, no need to consult anything with me :). I think making a dedicated organization or creating a fork in an existing one is the way to go, but it would be awesome if @folke could give his opinion regarding that before (that's actually the reason why I opened this issue)

**Comment by HungryJoe** [comment]
@bellini666 Since you seem interested in maintaining Trouble going forwards, I'd want to add you as an Owner on this hypothetical organization if you're interested; same with @folke. That's the main reason I want confirmation from y'all.

What existing organization would you want to fork Trouble in? The [Neovim one](https://github.com/neovim/)?

**Comment by tjdevries** [comment]
we could definitely put this in nvim-lua if someone wanted to maintain it there (I wouldn't have time to do so, but it's a cool plugin).

**Comment by bellini666** [comment]
> @bellini666 Since you seem interested in maintaining Trouble going forwards, I'd want to add you as an Owner on this hypothetical organization if you're interested; same with @folke. That's the main reason I want confirmation from y'all.

No, I actually don't want to maintain it :). I can help from time to time by doing some work and opening some PRs, but I'm unfortunately lacking time to maintain another project.

> we could definitely put this in nvim-lua if someone wanted to maintain it there (I wouldn't have time to do so, but it's a cool plugin).

I agree!

**Comment by HungryJoe** [comment]
> > @bellini666 Since you seem interested in maintaining Trouble going forwards, I'd want to add you as an Owner on this hypothetical organization if you're interested; same with @folke. That's the main reason I want confirmation from y'all.
> 
> No, I actually don't want to maintain it :). I can help from time to time by doing some work and opening some PRs, but I'm unfortunately lacking time to maintain another project.
That's fair enough, sorry for assuming.

> we could definitely put this in nvim-lua if someone wanted to maintain it there (I wouldn't have time to do so, but it's a cool plugin).
Awesome, thanks! Let me first look through the list of forks and see if any of the actively maintained ones have owners interested in making their fork the "canonical" one going forwards. Otherwise, I'd be willing to maintain Trouble as part of `nvim-lua`.

**Comment by pisetski** [comment]
Any updates @HungryJoe ? 🤔

**Comment by HungryJoe** [comment]
After giving it some thought, I'd like to maintain Trouble as part of `nvim-lua`. Although I write FOSS for a living, I have no experience maintaining a community-driven project. I've also never contributed to this repo. In fact, my only qualifications are that I love Trouble and want to help ensure it's survival, and I'm willing to put a few hours per week towards that goal.

I think the next steps are to see what contributors think and, if y'all are agreeable, see if @folke would be willing to move his fork into nvim-lua so that we don't lose existing PR's and Issues. For the former, I was thinking **contributors** (including folks whose first PR is still open) could **react to this message** with :thumbsup: **to approve** and :thumbsdown: **to reject** my taking over as maintainer; once there are a few reactions, let's say from 6 contributors, the reaction with the most votes will win. Let me know if that sounds overly formal or slow or democratic, I'm also happy to take over by virtue of being the only one willing to do so 🙂

**Comment by bellini666** [comment]
> Did anyting happen with this?

AFAIK, folke is back maintaining this repo, thus making this issue invalid.

I'm going to close this as it now.
