### ISSUE TITLE
Add support for lsp_incoming_calls provider

### ISSUE THREAD

**Issue by monopoly-db** [folke/trouble.nvim#222]
It'll be very useful to cycle through incoming calls by directly opening lsp_incoming_calls results in Trouble rather than having to do so by going to Telescope first.

**Comment by natdm** [comment]
This would be great to see. Incoming and outgoing as well. Love trouble!

**Comment by shahamran** [comment]
Almost opened another feature request, requesting "call hierarchy".
Then I remembered that the technical name for it in LSP world is incoming_calls, and found this :)
So I'll add this comment here, both to show interest in this feature, and for the "call hierarchy" keyword to show up in search.

**Comment by folke** [comment]
I may add this to v3.

**Comment by folke** [comment]
Added!

**Comment by shahamran** [comment]
Awesome! thanks!

**Comment by shahamran** [comment]
Hi @folke, I tried it out, and it's not exactly what I expected from a call-hierarchy UI.

In such UI I expect the incoming calls entries to recursively have their parents in the tree as well. See: <https://github.com/marcomayer/calltree.nvim>.
This way you could easily see the "call stack" of a function you're inspecting, and quickly jump to any of its ancestors.

I thought that since `trouble` is a tree UI, it'd be a good fit for such use-case. What do you think?
