### ISSUE TITLE
bug: two line error messages concatenated without space inbetween (Rust analyzer errors)

### ISSUE THREAD

**Issue by kting28** [folke/trouble.nvim#279]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

Ubuntu 22.0

### Describe the bug

![image](https://user-images.githubusercontent.com/24449116/236634796-321f9c3b-7f89-4503-95d5-fd3f9964b963.png)

The actual diagnostic messages from rust analyzer contains 2 lines:

```
1: cannot borrow `producer` as mutable more than once at a time
second mutable borrow occurs here (rustc)
```

### Steps To Reproduce

1. neovim with rust analyzer set up. Create any errors that has two lines.

### Expected Behavior

At least a space should be introduced when the two lines are joined together.

### Repro

```Lua
don't think this is needed.
```

**Comment by Diablo-D3** [comment]
As a rust user, I, too, have this issue.

My suggested fix is that multiple lines show in each item, as that would be the most ergonomically correct interpretation.

**Comment by MariaSolOs** [comment]
It seems like this is by design: https://github.com/folke/trouble.nvim/blob/20d1b30d6925213abece21d35858a16e11d1e9fc/lua/trouble/util.lua#L180

**Comment by MariaSolOs** [comment]
Okay I tried something in #305. Gotta wait to hear back from @folke regarding if this should be behind a setting, since this changes the layout a bit. My proposal is to display the diagnostic source and code in its own line, and have each related diagnostic below it.

A preview of how this looks:
<img width="1022" alt="image" src="https://github.com/folke/trouble.nvim/assets/62502207/e2b64820-39b1-4cd0-b155-a20de6c52f35">

Note that this also affects single line diagnostics (I'm open to not changing these though):
<img width="458" alt="image" src="https://github.com/folke/trouble.nvim/assets/62502207/ed0d1514-a80b-402c-9f69-33272f24ec0c">


What do you think? :)

**Comment by kting28** [comment]
May be leave single line alone ?

**Comment by MariaSolOs** [comment]
@kting28 yeah I think it would be better to keep the compact format for single-line diagnostics. I'm also debating whether have the diagnostic icon for each line of multiline diagnostics (as in the picture above shows) or just have it before the diagnostic source and position...

**Comment by eatgrass** [comment]
I think it would be great if we can `fold` and `unfold` the multiline diagnostics

**Comment by MariaSolOs** [comment]
Okay this is what it looks like with the latest commit:
<img width="540" alt="image" src="https://github.com/folke/trouble.nvim/assets/62502207/de30c5c6-847a-4420-b559-becec8702235">

As for folding, it might be beyond my expertise, but I'll do my best :)

**Comment by MariaSolOs** [comment]
I also want to wait for @folke's blessing before I continue to make sure these are changes that he approves.

**Comment by MariaSolOs** [comment]
After looking at it more closely, I think that keeping the icon besides the diagnostic code looks better:

<img width="830" alt="image" src="https://github.com/folke/trouble.nvim/assets/62502207/0ea9540f-f1b6-42af-a70b-e5c55c6fafab">
