### ISSUE TITLE
Ability to ignore certain errors

### ISSUE THREAD

**Issue by languitar** [folke/trouble.nvim#35]
I have a Python project that uses the [attrs](https://github.com/python-attrs/attrs) library. The language server pyright doesn't support attrs and always reports errors when an attrs class is used. Therefore, the list provided in this plugin always contains a known set of things that I simply can't change. Having some kind of filtering possibility to ignore known errors would help very much in this situation.

**Comment by folke** [comment]
That is out of scope for this plugin. Please refer to the [pyright docs](https://github.com/microsoft/pyright/blob/main/docs/configuration.md) to properly configure your lsp server.

There seem to be settings to ignore diagnostics from certain modules etc...

**Comment by languitar** [comment]
The only thing that I can find are the generic "# type: ignore" settings, which would also prevent other tools from performing checks. Do you refer to another setting in the pyright config you linked?

Adding such a thing to trouble.nvim would mean admitting that LSPs are sometime error prone or also that some projects have a lot of issues in the beginning and some way of navigating to the relevant diagnostics could improve such situations.

**Comment by folke** [comment]
> ignore [array of paths, optional]: Paths of directories or files whose diagnostic output (errors and warnings) should be suppressed even if they are an included file or within the transitive closure of an included file. Paths may contain wildcard characters ** (a directory or multiple levels of directories), * (a sequence of zero or more characters), or ? (a single character).

**Comment by folke** [comment]
Apart from that, I'm sure you can define disable rules in your code as part of the configuration or inline.

**Comment by languitar** [comment]
> > ignore [array of paths, optional]: Paths of directories or files whose diagnostic output (errors and warnings) should be suppressed even if they are an included file or within the transitive closure of an included file. Paths may contain wildcard characters ** (a directory or multiple levels of directories), * (a sequence of zero or more characters), or ? (a single character).

The LSP generates false-positive errors inside my main code base when using attrs-based classes. Therefore, simply ignoring all project code is not a good idea ;-)

> Apart from that, I'm sure you can define disable rules in your code as part of the configuration or inline.

Yes, I can ignore that, but then also other tools used in the CI setup performing further linting will ignore these constructs, although they easily support this. So there's no simple solution to fulfill all constraints and therefore I currently have to live with a whole set of false-positive reports in vim.

**Comment by languitar** [comment]
In case you're interested, here are some of the discussions regarding these pyright-specific issues: https://github.com/microsoft/pyright/issues/146

**Comment by jason0x43** [comment]
I know this issue is closed, by I think this would be a worthwhile feature. Pyright in particular is a good example. It emits hints for unused parameters. That's a very reasonable use of hints. However, when I look at the list of diagnostics in Trouble, it may be full of hints. I don't want to entirely filter them out of the list of published diagnostics because they may enable meaningful visual cues (like dimming unused function parameters). However, they don't need to show up in the list of diagnostics shown by Trouble. Even a severity level filter would be useful (so that any hints could be left out).

**Comment by ELLIOTTCABLE** [comment]
I'm just dropping in to hope this gets addressed specifically by Trouble.nvim, not upstream in the LSPs — like it or note *a lot* of LSP projects don't actually allow any sort of configuration to disable *suggestions*, specifically because they expect that behaviour to happen at the editor-level (unlike *errors*, which need to have mirrored behaviour between the editor and the command-line; and thus need to be configured in a shared, project-local location.)

Another *huge* example here is TypeScript: `@ts-ignore` and tons of configuration-file options exist for *errors*; but zero configuration options whatsoever exist for *suggestions.* (For whatever it's worth, this *is* being tracked upstream there as a feature-request; see Microsoft/TypeScript#28825; but it doesn't seem to have gotten much traction for exactly the reason described here: pretty much all the editors have settings to configure this — VScode and Atom, at least, that I know of; and it doesn't affect the CLI users, *only* the LSP.)

Anyway: here's my impassioned plea that Trouble.nvim give us feature-parity with VScode, Atom, etc LSP clients, and allow us to filter diagnostics at the *client* end; even if only to deal with 'misbehaving' tools!
