### ISSUE TITLE
bug v3: missing icons

### ISSUE THREAD

**Issue by wojciech-kulik** [folke/trouble.nvim#395]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2723+g981301d11

### Operating system/version

macOS 14.4

### Describe the bug

In nightly nvim icons are not visible. I'm using `Trouble quickfix toggle`. On v0.9.5 icons appear correctly. If I switch from dev branch to main it also works.

### Steps To Reproduce

1. Use Trouble from dev branch
2. Open NVIM v0.10.0-dev-2723+g981301d11
3. Populate quickfix with warning and errors
4. `Trouble quickfix toggle`

Instead of icons `E` and `W` appear.

### Expected Behavior

Warning and error icons should appear on the list

**Comment by folke** [comment]
On nightly you need to properly configure icons with `vim.diagnostic.config`

**Comment by wojciech-kulik** [comment]
It worked, thank you! 🍻

**Comment by mawkler** [comment]
@folke I have `signs = false` in `vim.diagnostic.config` because I've put the sign icons in front of the virtual text using `virtual_text.prefix`, which means that diagnostics in the signcolumn are redundant. But that means that I don't get any icons in trouble either. Is there some way to fix that?
