### ISSUE TITLE
feature: close all views

### ISSUE THREAD

**Issue by abhinavnatarajan** [folke/trouble.nvim#456]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

In Trouble v2, if some view was open and I used `:TroubleToggle someotherview`, the active view would be closed and the new view would be opened. This meant that I could use trouble as a console with a fixed window position, with at most one Trouble window active at any given moment. 
In Trouble v3, toggling a new view does not close currently active views, so for example if the diagnostics view is open and I also open the qflist then I have two trouble windows open.

### Describe the solution you'd like

Allow passing in `"*"` as a mode parameter for `trouble.close()`. That way I can close all windows, and use this in the keybind I have for toggling views. Ideally this should also be allowed for `trouble.is_open()` to accommodate setups with more nuanced window management.

### Describe alternatives you've considered

Technically my issue can be solved by calling `trouble.close()` for every possible view, but this is unecessarily verbose, and brittle because the code would have to be modified whenever a new view is added to Trouble.

**Comment by folke** [comment]
If you call either close or is_open without any options, it will check if any view is open or will close the most recent view.

To close all:

```lua
local view = trouble.close()
while view do
  view = trouble.close()
end
```

**Comment by JohnWilliston** [comment]
I came across this today because I find the trouble plugin often leaves windows open. The function you provide very helpfully closes all the views, but it leaves their resulting windows open. For example, I often have diagnostics open in a window at the bottom and symbols open in a window at the right. I'd like to find a simple way to close both the trouble views and the windows that were opened when I toggled them. Any suggestions?
