### ISSUE TITLE
Execute commands on each line/file?

### ISSUE THREAD

**Issue by samtgarson** [folke/trouble.nvim#53]
Hello! Trouble looks great, the only thing stopping me using it is the ability to execute commands on each file in the list.

My primary usecase is project-wide search and replace, example workflow:
1. Execute a project-wide search (using e.g. Telescope or fzf)
2. Open the results in a quickfix window
3. Use `cdo` or `cfdo` to do a find/replace on each file or each result

Is anything like this possible with Trouble, or would you consider it a useful feature? Thanks ✌️ 

_(side note: also open to hearing about other workflows for project wide find/replace!)_

**Comment by folke** [comment]
I would stick with quicklists for that. The goal of Trouble is not to re-implement all quicklist/locllist functionality.

**Comment by joehannes** [comment]
just stumbled bout the same situation. would have been nice to be able to do this.
since I installed trouble (I like it) it seems it's taken over the default telescope 'send to quickfix' shortcut.
now I can't do what I was about to do and need to investigate, ...

**Comment by joehannes** [comment]
actually, I was mistaken... it actually works just fine with trouble - exactly as it works with default quickfix.
@samtgarson ... you should try trouble after all, this feature you need is working by default.
@folke ... can you double check and confirm since you kinda stated it's not possible?

![2021-07-21 16 45 38](https://user-images.githubusercontent.com/63741107/126558552-8410109e-fc4c-4d8d-b4e9-2e2efb199e34.jpeg)

**Comment by folke** [comment]
@joehannes that has nothing todo with Trouble? :)

Telescope can push results in the quickfix list and there you can use `cdo` etc.

I believe op wanted to be able to use `cdo` in the Trouble window. And I'm not planning on supporting that, since you can use the quickfix and loclist lists for that.

**Comment by folke** [comment]
Also, Trouble does not take over sending items to the quickfix list.

**Comment by joehannes** [comment]
hmmm, so I'm mistaken again?? well, it works and I'm happy.

look at my train of thoughts if you will:
---
situation:
live grep just as op described
sending it to quickfix just as op described
finding quickfix enhanced by telescope (and i thought trouble ... i did have telescope before I added trouble and there was no additional preview nor would it state trouble underneath the window in the statusbar, but now both are there, so I really thought/think this is trouble, but I guess who am I to argue with the creator of trouble, hehe, that's why I sent the img and thought you should reconsider)
cfdo ... works
---
usage:
if I want to project wide refactor in something the LSP doesn't understand like CSS in CSS plus CLJS (html templating of some unsupported sort) ... I need to find/replace ... there's also no way trouble would help with this anyway, since there's no real errors or warnings, I just want to refactor.
But since I think the quickfix window is replaced by a trouble-enhanced-quickfix-window (this is where I though op wanted to know if it then works .. but on second thought, if he installed trouble and got to this point, why didn't he succeed??) .. I was not sure this would work.
In the beginning I tried and thought I had not succeeded as :cfdo didn't autosave and I forgot to save the changed files, grepping a new ... thinking it didn't work as the same old patterns were found ...

ok, cheers, J

**Comment by joehannes** [comment]
Also I'm pretty sure:
* trouble did take over the default shortcut (Ctrl + Shift + Q) .. since I didn't configure it and this is what is happening
* the quickfix-window is replaced by trouble since I even can adjust this in trouble config (and did try and the window did change on config-changes)

so ... I'm kinda confused why u are saying it is not so ...

this is the line in trouble.setup{} that changes this quickfix window (so I can actually see, yes trouble is taking over the quickfix window that is sent to by telescope):
```lua
    mode = "lsp_document_diagnostics", -- "lsp_workspace_diagnostics", "lsp_document_diagnostics", "quickfix", "lsp_references", "loclist"
```

**Comment by folke** [comment]
The `mode = quickfix`, simply means that if you open Trouble, it will read in the quickfix list and display it in Trouble. The actual quickfix list is still there.

I don't take over anything in Telescope.

You **can** configure Telescope and add a shortcut to send results to Trouble though. More info about that [here](https://github.com/folke/trouble.nvim#telescope)

**Comment by folke** [comment]
@joehannes see the example below. Here I opened a search in Telescope and did `<C-q>` to send the results to a quickfix list (bottom split) and `<c-t>` to send the results to Trouble (middle split)

![image](https://user-images.githubusercontent.com/292349/126561628-33909dd3-f7da-4fa8-b99b-5701f34eb36a.png)

**Comment by folke** [comment]
You can use `cdo` and `cfdo` in the quickfix list, but not in the Trouble list

**Comment by joehannes** [comment]
let me search how my telescope is configured with that shortcut, because I don't get it how that is possible :-)

**Comment by joehannes** [comment]
Actually I'm confused again ...

I couldn't find any overriding config shortcut for c-q ...

Anyway I tried the c-t and now see that the trouble list looks different :-)
But ... I could do the :cfdo command in the trouble window anyway and it worked ...
I successfully just replaced 'button' with 'mistermister' via `:cfdo %s/button/mistermister/g` in the trouble window

so maybe it's something about my telescope config after all, I don't know. 

Ok, since my guesses got less content each step we move on and I'm new to trouble anyway and don't know much ...

Thx for the conversation :-)

**Comment by joehannes** [comment]
ok, just to make up for the misinformation from my side:

Just found 'cfdo' in the trouble window only operates on the current buffer ... so it doesn't work after all, whatever the reason

Cheers, J
